/*
 * KubernetesUserManager - API
 *
 * This is a backend API server documentation for KubernetesUserManager  Some useful links: - [Jira](https://samuelus.atlassian.net/jira/software/projects/ZPI/boards/4) - [Confluence](https://samuelus.atlassian.net/wiki/spaces/ZPI/overview)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Generic Kubernetes resource
type Resource struct {
	// API version of the resource
	ApiVersion string `json:"apiVersion,omitempty"`
	// Kind of the resource
	Kind string `json:"kind,omitempty"`
	// Specification of the metadata
	Metadata *interface{} `json:"metadata,omitempty"`
	// Specification of the resource
	Spec *interface{} `json:"spec,omitempty"`
	// Current status of the resource
	Status *interface{} `json:"status,omitempty"`
}
