/*
 * KubernetesUserManager - API
 *
 * This is a backend API server documentation for KubernetesUserManager  Some useful links: - [Jira](https://samuelus.atlassian.net/jira/software/projects/ZPI/boards/4) - [Confluence](https://samuelus.atlassian.net/wiki/spaces/ZPI/overview)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api

import (
	"github.com/ZPI-2024-25/KubernetesUserManager/go/controllers"
	"net/http"
)

func CreateClusterResource(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func CreateNamespacedResource(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func DeleteClusterResource(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func DeleteNamespacedResource(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func GetClusterResource(w http.ResponseWriter, r *http.Request) {
	controllers.GetClusterResourceController(w, r)
}

func GetNamespacedResource(w http.ResponseWriter, r *http.Request) {
	controllers.GetNamespacedResourceController(w, r)
}

func ListClusterResources(w http.ResponseWriter, r *http.Request) {
	controllers.ListClusterResourcesController(w, r)
}

func ListNamespacedResources(w http.ResponseWriter, r *http.Request) {
	controllers.ListNamespacedResourcesController(w, r)
}

func UpdateClusterResource(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func UpdateNamespacedResource(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
